// Constantes de clínicas permitidas
export const ALLOWED_CLINICS = {
  coa: 'coa',
  aviva: 'aviva',
  oftalmomedic: 'oftalmomedic',
  sedaredent: 'sedaredent',
  auna: 'auna',
  avendao: 'avendao',
  d_dental: '3d-dental',
  wirealigner: 'wirealigner',
  arthrosalud: 'arthrosalud',
  romamedic: 'romamedic',
  cirugiaplasmartinez: 'cirugiaplasmartinez',
  oftalmosalud: 'oftalmosalud',
  ricardo_palma: 'ricardo-palma',
  santa_isabel: 'santa-isabel',
  fertivida: 'fertivida',
  jrc: 'jrc',
  andrea_contreras: 'andrea-contreras',
  multident: 'multident',
  bolivar: 'bolivar',
  bariasthetic: 'bariasthetic',
  porvenir: 'porvenir',
  cliniesthetic: 'cliniesthetic',
  dental_alemana: 'dental-alemana',
  multident_franquicias: 'multident-franquicias',
  sannens: 'sannens',
  ama: 'ama',
  longtail: 'longtail',
  hoshejoo: 'hoshe-joo',
  leon: 'leon',
  ortodonciavasquez: 'ortodonciavasquez',
  fisiodinamica: 'fisiodinamica',
  biodentix: 'biodentix',
  mvdental: 'mvdental',
  audiphone: 'audiphone',
  audiphone_callcenter: 'audiphone-callcenter',
  mundoral: 'mundoral',
  virtualdent: 'virtualdent',
  dentallonga: 'dentallonga',
  estheticdentalcenter: 'estheticdentalcenter',
  karisma: 'karisma',
};

// Constantes de sedes por clínica
export const CLINIC_SEDES: Record<string, string[]> = {
  coa: ['Sede 1', 'Sede 2'],
  aviva: ['Sede 1', 'Sede 2'],
  oftalmomedic: ['Sede 1', 'Sede 2'],
  sedaredent: ['Sede 1', 'Sede 2'],
  auna: ['Sede 1', 'Sede 2'],
  avendao: ['Sede 1', 'Sede 2'],
  d_dental: ['Sede 1', 'Sede 2'],
  wirealigner: ['Sede 1', 'Sede 2'],
  arthrosalud: ['Sede 1', 'Sede 2'],
  romamedic: ['Sede 1', 'Sede 2'],
  cirugiaplasmartinez: ['Sede 1', 'Sede 2'],
  oftalmosalud: ['Sede 1', 'Sede 2'],
  ricardo_palma: ['Sede 1', 'Sede 2'],
  santa_isabel: ['Sede 1', 'Sede 2'],
  fertivida: ['Sede 1', 'Sede 2'],
  jrc: ['Sede 1', 'Sede 2'],
  andrea_contreras: ['Sede 1', 'Sede 2'],
  multident: ['Sede 1', 'Sede 2'],
  bolivar: ['Sede 1', 'Sede 2'],
  bariasthetic: ['Sede 1', 'Sede 2'],
  porvenir: ['Sede 1', 'Sede 2'],
  cliniesthetic: ['Sede 1', 'Sede 2'],
  dental_alemana: ['Sede 1', 'Sede 2'],
  multident_franquicias: ['Sede 1', 'Sede 2'],
  sannens: ['Sede 1', 'Sede 2'],
  ama: ['Sede 1', 'Sede 2'],
  longtail: ['Sede 1', 'Sede 2'],
  hoshejoo: ['Sede 1', 'Sede 2'],
  leon: ['Sede 1', 'Sede 2'],
  ortodonciavasquez: ['Sede 1', 'Sede 2'],
  fisiodinamica: ['Sede 1', 'Sede 2'],
  biodentix: ['Sede 1', 'Sede 2'],
  mvdental: ['Sede 1', 'Sede 2'],
  audiphone: ['Sede 1', 'Sede 2'],
  audiphone_callcenter: ['Sede 1', 'Sede 2'],
  mundoral: ['Sede 1', 'Sede 2'],
  virtualdent: ['Sede 1', 'Sede 2'],
  dentallonga: ['Sede 1', 'Sede 2'],
  estheticdentalcenter: ['Sede 1', 'Sede 2'],
  karisma: ['Sede 1', 'Sede 2'],
};