// Constantes de clínicas permitidas
export const ALLOWED_CLINICS = {
  "coa": 'coa',
  "aviva": 'aviva',
  "oftalmomedic": 'oftalmomedic',
  "sedaredent": 'sedaredent',
  "auna": 'auna',
  "avendao": 'avendao',
  "3d_dental": '3d-dental',
  "wirealigner": 'wirealigner',
  "arthrosalud": 'arthrosalud',
  "romamedic": 'romamedic',
  "cirugiaplasmartinez": 'cirugiaplasmartinez',
  "oftalmosalud": 'oftalmosalud',
  "ricardo_palma": 'ricardo-palma',
  "santa_isabel": 'santa-isabel',
  "fertivida": 'fertivida',
  "jrc": 'jrc',
  "andrea_contreras": 'andrea-contreras',
  "multident": 'multident',
  "bolivar": 'bolivar',
  "bariasthetic": 'bariasthetic',
  "porvenir": 'porvenir',
  "cliniesthetic": 'cliniesthetic',
  "dental_alemana": 'dental-alemana',
  "multident_franquicias": 'multident-franquicias',
  "sannens": 'sannens',
  "ama": 'ama',
  "longtail": 'longtail',
  "hoshejoo": 'hoshe-joo',
  "leon": 'leon',
  "ortodonciavasquez": 'ortodonciavasquez',
  "fisiodinamica": 'fisiodinamica',
  "biodentix": 'biodentix',
  "mvdental": 'mvdental',
  "audiphone": 'audiphone',
  "audiphone_callcenter": 'audiphone-callcenter',
  "mundoral": 'mundoral',
  "virtualdent": 'virtualdent',
  "dentallonga": 'dentallonga',
  "estheticdentalcenter": 'estheticdentalcenter',
  "karisma": 'karisma',
  //clinicas longtail
  "candila": 'candila',
  "odontovital": 'odontovital',
  "sueldo_medical": 'sueldo-medical',
  "velarde_alvarez": 'velarde-alvarez',
  "odontosalud": 'odontosalud',
  "r&r_dentix": 'r&r-dentix',
  "villasonrisa": 'villasonrisa',
  "corporal_age": 'corporal-age',
  "expert_dent": 'expert-dent',
  "clinica_europea": 'clinica-europea',
  "clinica_renacer": 'clinica-renacer',
  "smile_design": 'smile-design',
  "health_smiling": 'health-smiling',
  "smile_empire": 'smile-empire',
  "vdent": 'vdent',
  "maxilo_group": 'maxilo-group',
  "fisiobaric": 'fisiobaric',
  "javaMedic": 'javaMedic',
  "juan_carlos_meza": 'juan-carlos-meza',
  "fernando_rodriguez": 'fernando-rodriguez',
  "proyecto_in_utero": 'proyecto-in-utero',
  "mawi_dental_studio": 'mawi-dental-studio',
  "dr_cow": 'dr-cow',
  "empateeth": 'empateeth',
  "obesidad_cuzco": 'obesidad-cuzco',
  "jackeline_anicama": 'jackeline-anicama',
  "multigint": 'multigint',


};

// Constantes de sedes por clínica
export const CLINIC_SEDES: Record<string, string[]> = {
  "coa": ['San Isidro', 'Principal', 'Santa Catalina', 'Cercado de Lima', 'Zárate', 'Comas', 'Javier Prado', 'Barranco',  'Callao', 'Jesús María', 'Los Olivos', 'Miraflores', 'San Juan de Miraflores', 'Surco', 'La Molina', 'Los Jardines', 'Pueblo Libre', 'Ica'],
  "aviva": ['Los Olivos', 'Cercado de Lima'],
  "oftalmomedic": ['Lince', 'Los Olivos'],
  "sedaredent": ['Lince', 'Los Olivos'],
  "auna": ['san borja', 'miraflores', 'bellavista', 'arequipa'],
  "avendao": ['Miraflores'],
  "3d-dental": ['Miraflores', 'Chacarilla', 'Arequipa'],
  "wirealigner": ['Principal'],
  "arthrosalud": ['Principal', 'Lima'],
  "romamedic": ['Principal', 'Trujillo', 'Surco', 'Los Olivos'],
  "cirugiaplasmartinez": ['Santiago de Surco'],
  "oftalmosalud": ['Arequipa', 'San Isidro', 'San Juan de Miraflores', 'Los Olivos'],
  "ricardo-palma": ['Principal'], //falta data
  "santa-isabel": ['Principal'], //falta data
  "fertivida": ['San Isidro', 'Ayacucho', 'Ate'],
  "jrc": ['Principal'],   //falta data
  "andrea-contreras": ['San Miguel', 'Miraflores', 'San Juan de Lurigancho', 'Los Olivos'],
  "multident": [ 'Infinity','Lince', 'Angamos', 'La Merced' ],
  "bolivar": ['Los Olivos', 'Pueblo Libre', 'San Juan de Lurigancho', 'Miraflores'],
  "bariasthetic": ['Magdalena'],
  "porvenir": ['Principal'],
  "cliniesthetic": ['Javier Prado'],
  "dental-alemana": ['Principal'],
  "multident-franquicias": ['Monterrico','Chacarilla', 'Magdalena 2', 'Javier Prado Oeste', 'San Felipe', 'Pardo'],
  "sannens": ['Surquillo'],
  "ama": ['Principal'],
  //longtail: ['Sede 1', 'Sede 2'],
  "hoshe-joo": ['Principal'],
  "leon": ['Miraflores', 'Los Olivos'],
  "ortodonciavasquez": ['San Borja', 'La Molina'],
  "fisiodinamica": ['Miraflores', 'Surco'],
  "biodentix": ['Principal', 'Miraflores'],
  "mvdental": ['Surco', 'Lince', 'Surquillo'],
  "audiphone": ['Javier Prado', 'Miraflores', 'San Miguel', 'Los Olivos', 'San Juan de Lurigancho', 'Santa Anita', 'Cusco', 'Arequipa'],
  "audiphone-callcenter": ['Javier Prado', 'Miraflores', 'San Miguel', 'Los Olivos', 'San Juan de Lurigancho', 'Santa Anita', 'Cusco', 'Arequipa'],
  "mundoral": ['Principal', 'San Isidro', 'San Juan de Lurigancho', 'Santa Anita'],
  "virtualdent": ['Miraflores', 'San Borja'],
  "dentallonga": ['Lince', 'La Molina'],
  "estheticdentalcenter": ['larcomar', 'parque kennedy', 'surco', 'san martín de porres'],
  "karisma": ['Principal'], //falta data
  //clinicas longtail
  "candila": ['Principal'],
  "odontovital": ['Principal'],
  "sueldo-medical": ['Principal'],
  "velarde-alvarez": ['Principal'],
  "odontosalud": ['Principal'],
  "r&r-dentix": ['Principal'],
  "villasonrisa": ['Principal'],
  "corporal-age": ['Angamos'],
  "expert-dent": ['Principal'],
  "clinica-europea": ['Principal'],
  "clinica-renacer": ['miraflores'],
  "smile-design": ['Principal'],
  "health-smiling": ['Principal'],
  "smile-empire": ['Principal'],
  "vdent": ['Principal'],
  "maxilo-group": ['Principal'],
  "fisiobaric": ['Principal'],
  "javaMedic": ['Principal'],
  "juan-carlos-meza": ['Principal'],
  "fernando-rodriguez": ['Principal'],
  "proyecto-in-utero": ['Principal'],
  "mawi-dental-studio": ['Principal'],
  "dr-cow": ['Principal'],
  "empateeth": ['Principal'],
  "obesidad-cuzco": ['Principal'],
  "jackeline-anicama": ['Principal'],
  "multigint": ['Principal'],
};